### ISSUE TITLE
[Bug] Table dimensions are sometimes hidden by the cursor.

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#101]
**Describe the bug**
This is not a bug per se, this is more of a UI/UX thing that is rather anoying and should be fixed.
The thing is that then creating a table its dimentions (number of columns and rows) are often hiden by the cursor (screenshot 1). While it is quite easy to figure out the dimensions even if the they are hiden it still requires a lot more thinking and mental load than necessary.

**Expected behavior**
Display the dimensions somewhere else (could work as an addition to the current way they are presented). Google Docs do it bellow the table selection while Microsoft word does it above which has the added benefit of not moving thus being easer to read while selecting larger tables.

**Screenshots**
Screenshot 1:
![Cryptee](https://user-images.githubusercontent.com/49041398/108988983-0158df80-768d-11eb-8681-e4fbaf9d01da.PNG)
 *The windows screenshot tool removes the cursor so I hastly edited the photo, but the point still stands and it's prety similar to how it actually looks*

Examples of how other programs to table insertion:
![Gdocs](https://user-images.githubusercontent.com/49041398/108988999-087fed80-768d-11eb-8909-df5dadfe743e.gif)
![Word](https://user-images.githubusercontent.com/49041398/108989009-0a49b100-768d-11eb-97e1-00cada842592.gif)
*The dimesions of the table are never hidden*

**Comment by johnozbay** [comment]
Hey there! 👋🏻

Love this! We'll make this happen and roll it out with the upcoming release! 
Thanks a lot for sending it over! Will ping this thread when it's out!

**Comment by johnozbay** [comment]
Also – thank you so much for the GIFs, this was exceptionally helpful and amazing!

**Comment by johnozbay** [comment]
Done! Coming up with the next release! 

![image](https://user-images.githubusercontent.com/611338/109039703-c202b100-76d5-11eb-917a-401478467c96.png)

I've added this in the alpha version now and linked this issue to our internal issue/release tracker.
Once the update with this feature is out (should be in a day or two), this issue will be closed automatically, and you'll get a notification!

Thank you so much for this fantastic feedback!

**Comment by johnozbay** [comment]
p.s. – on mobile / touch devices without cursors since there's no 'hovering' the cells will still show the column & row numbers.
