### ISSUE TITLE
Implement confirmation prompts when selecting a subscription plan.

### ISSUE THREAD

**Issue by jackcoble** [cryptee/web-client#103]
**Is your feature request related to a problem? Please describe.**
This is an issue that I ran into several minutes ago when looking around at the Crypt.ee subscription amounts. I am already a paid user of the 10GB for 3 euros per month plan so my payment method is already on file, but was looking at how much I could potentially save by being charged yearly for the different plans.

As Cryptee only shows the amount of money saved per year on the subscriptions page, I was hoping to click on the plan to find out some more information. However, this resulted in the plan being activated straight away and then my payment method being charged. I did this by accident. This could be incredibly frustrating for some users who are simply trying to find out more information about a plan and then they are charged.

**Describe the solution you'd like**
I think it would be beneficial to provide a confirmation pop-up of the total subscription amount right before the subscription plan is selected and the payment is processed. The user must click on "confirm" before the plan is activated and a payment is taken. If the "cancel" button is clicked, no further action is taken.

Please excuse the shocking diagram 😅, but something like this:
![image](https://user-images.githubusercontent.com/26122014/109079287-a52aa580-76f6-11eb-8d53-ba69992df804.png)

**Additional context**
![image](https://user-images.githubusercontent.com/26122014/109078440-3dc02600-76f5-11eb-83ad-957c8946ce59.png)
This was my view of the yearly subscriptions page before clicking on a subscription plan.

![image](https://user-images.githubusercontent.com/26122014/109078794-d5257900-76f5-11eb-9279-73e452538c80.png)
This was the popup I received right after selecting on the plan, with the intention to find out more information about it.

![image](https://user-images.githubusercontent.com/26122014/109078890-0605ae00-76f6-11eb-8a16-80efbc6ac551.png)
My payment method on file being charged right after selecting the plan.

I hope everything I've mentioned here is correct. If not, then please feel free to close this issue.

**Comment by johnozbay** [comment]
Hey Jack! 👋🏻

Thanks a million for filing this! It seems we fucked up big time with this one. 
Reached out to you via our helpdesk just now and issued a full refund.

We're working on a fix right now and will release an update addressing this today. 
There was supposed to be popup like "your payment will be prorated and you can start using the plan right away" type dialog with a confirmation box. 

Deeply appreciate your kindness and understanding despite our royal fuckup! 
I owe you one. 🙏🏻

**Comment by jackcoble** [comment]
Hello John! :wave: 

I've just read your email response. Thank you for getting back to me so quickly and addressing the issue! 🙂 
Please keep up the great work, it's an awesome service you are providing! Looking forward to what the future holds!

Have a great day!

**Comment by johnozbay** [comment]
Hey Jack! 
You're so very welcome and _thank you_ **so much** for your kind support and patience with all this!
Once again my apologies that it happened in the first place. 

p.s. – we've already fixed this in our alpha, running a bunch of tests now – and will push this fix out to live shortly to avoid more chaos 😳  I've linked this issue to our internal issue/release tracker, once the update with this fix is out, this issue will be closed automatically, and you'll get a notification!

Have a wonderful day yourself too! 
And needless to say please feel free to ping me anytime if you run into any issues at all, always here! ✌🏻

**Comment by jackcoble** [comment]
No worries at all! I'm glad the issue has been fixed and is waiting to be pushed to live!
Hopefully you won't have to deal with some potentially angry customers if they wanted to _browse_ the different plans today! 😅

I'll be sure to file an issue or send you an email if I experience any problems in the future!
