### ISSUE TITLE
Inconsistent Logo Behavior

### ISSUE THREAD

**Issue by brendanperry** [cryptee/web-client#107]
**Describe the bug**
The logo acts differently in the documents section than it does in the photos section.

**To Reproduce**
1. Go to documents
2. The logo is white
3. Hover over the logo
4. The logo stays white

1. Go to photos
2. The logo is gray
3. Hover over the logo
4. The logo color changes to white

**Expected behavior**
I would expect the documents logo to behave the same as the photos logo.

**Screenshots**

https://user-images.githubusercontent.com/60938545/109101530-e28e3380-76f4-11eb-8314-8e2307a3e5c9.mov

**System Information (please complete the following information):**
 - Device: Macbook Pro 2016 15in
 - OS: Catalina
 - Browser: Brave
 - Browser Version [e.g. 22] Version 1.20.103 Chromium: 88.0.4324.152 (Official Build) (x86_64)
 - Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.] uBlock, Snowflake, Bitwarden, Dark reader (disabled for this test)
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole]
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network] VPN

**Additional context**
On mobile there is no hover of course, the icon always stays gray in photos and always white in documents.

**Comment by johnozbay** [comment]
LOVE this! 
Thank you for this! 
It's amazing to have someone else pay attention to these subtle little design details!
Fix coming out bundled with a bunch of other stuff shortly, issue will close itself once it's released! 🎉
