### ISSUE TITLE
[Bug] it is possible to scroll below the document edit area

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#111]
**Describe the bug**
It is possible to scroll below the document edit area.
When it is triggered the top part of the left menu is not accessible any more.

**To Reproduce**
1. open a document
2. hit page down or up
3. see screen shot below: the top section is not accessible ("search" section and Cryptee icon) and in the button section a new "move here" message is shown

**Expected behavior**
Page down / up is working as expected: only the document content is scrolled down / up, not the entire screen.

**Screenshots**

![image](https://user-images.githubusercontent.com/62843615/109329133-847b6080-785a-11eb-9df5-e695fb104f08.png)

**System Information (please complete the following information):**
 - Device: laptop
 - OS: Windows 10
 - Browser: Microsoft Edge (Chromium based)
 - Browser Version: 88.0.705.63 (Official build) (64-bit)
 - Browser Extensions / Add-ons / Content/Ad-Blockers: uBlock Origin (cosmetic filtering disabled)
 - Do you have any DNS-based content/ad-blockers? no
 - Are you on a managed network? no

**Additional context**
I have tested in Windows Edge only.

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Thanks a lot for filing this one and for the helpful screenshot! 
Looks like somehow Edge treats overflows differently than Chrome. no idea how or why.
  
We've managed to reproduce this and I've fixed this in the alpha version now and linked this issue to our internal issue/release tracker. Once the update with this fix is out (should be in a day or two), this issue will be closed automatically, and you'll get a notification!

Thank you so much for your help with this! 🎉

**Comment by johnozbay** [comment]
This should be fixed now but let me know if you bump into this again 👍🏻
Many thanks for filing this 🙏🏻

**Comment by BasilTomato** [comment]
Thank you, it is working fine in Edge v88.

**Comment by johnozbay** [comment]
Wooohoo! You're very welcome! 
Thank _you_ for reaching out with this bug 🎉
