### ISSUE TITLE
[Bug] Pasting opens the sidebar on iOS

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#116]
**Describe the bug**
Pasting text in a document causes the folders sidebar to open.

**To Reproduce**
1. Copy text
2. Paste text in a cryptee doc
3. Observe the sidebar opens

**Expected behavior**
Sidebar stays closed!

**Screenshots**
![8612FBC1-D3E7-4772-B08A-4DE3860E9CA6](https://user-images.githubusercontent.com/273696/110564627-02185980-8102-11eb-8b2b-b08e5dfc19d1.gif)

**System Information (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 14.4
 - Browser: Safari PWA

**Comment by johnozbay** [comment]
Hi there! 

Thanks a lot for filing this! 
We're aware of this nasty bug, and looking for a fix. 

We'll likely have to disable the slider/UI when the 'paste' event is triggered to prevent these. Looks like iOS likes to scroll the page when you paste stuff for some reason.

**Comment by johnozbay** [comment]
Hi there! 
We've just released an update and this should be fixed now. 
Give it a try and let me know! 

Many thanks for filing this and for your help once again! 🙏🏻
Best
J

**Comment by dhda** [comment]
Works great now, thank you!

**Comment by johnozbay** [comment]
Really happy to hear! You're very welcome, and thank **_you_** for reaching out with this! 🙏🏻
