### ISSUE TITLE
[Feature Request] Ability to create a shared-folder with other cryptee user(s)

### ISSUE THREAD

**Issue by lutopian** [cryptee/web-client#124]
**Is your feature request related to a problem? Please describe.**
So I am using Cryptee to store me & my gf's photos, as well as editing some of my personal documents.
Since there is no share or collaborate function currently, the only way that I can let my gf to upload our photos is giving her my login credentials, which obviously is not good on both privacy and security ends.

Not only that, by giving her my credentials, it means she can completely read/write whatever documents I'm working on.
which is... troublesome.

**Describe the solution you'd like**
a shared-folder function within the Cryptee ecosystem

**Additional context**
Just want to say I am very happy to find out about Cryptee! When I told my girlfriend that I was looking for a privacy-oriented cloud solution to replace our Google Photos, she was a bit hesitated. However, once I introduced her Cryptee, she was amazed by the UI/UX and the overall "feel of security" right away. That's how I convinced her to switch. Thank you for putting time and effort to make Cryptee happen!

(As a side note, more pricing plans available to narrow down the gaps between 10gb, 400gb, and 2tb would be great!)

**Comment by johnozbay** [comment]
Hi there, 

Thanks for filing this, your kind words and compliments! Deeply appreciate it! 🙏🏻
Glad to hear you're enjoying Cryptee overall!

Please take a look at this duplicate thread: https://github.com/cryptee/web-client/issues/122, where I gave an extensive answer. 
Will close this for the sake of keeping our issues as consolidated and clean as possible. ✌🏻

Best,
J
