### ISSUE TITLE
<u> tags in search results

### ISSUE THREAD

**Issue by quenousimporte** [cryptee/web-client#125]
**Describe the bug**
Some <u> tags are displayed in search results.

**To Reproduce**
1. Type something in the search area
2. Check the result list

**Screenshots**
![Capture d’écran 2021-06-11 111220](https://user-images.githubusercontent.com/76260127/121662739-f98b4280-caa5-11eb-95d2-a07232e7ca05.png)

**System Information**
 - Device: Laptop (also seen on Android 6)
 - OS: Windows 10
 - Browser: Brave
 - Browser Version: 1.25

**Comment by johnozbay** [comment]
Hi there! 
Thanks a million for filing this! 🙏🏻

Looks like we broke something in the last release and our automated tests didn't catch this one! 
We're on it now, and we'll release a fix for this right away in 12 - 24 hours.

Thanks!

**Comment by johnozbay** [comment]
Hi there, we've released a beta version ( `5792bf5` ) and it should address this problem. 
If possible could you try beta.crypt.ee and give it a go there? 
If you can confirm this is indeed fixed as well, we'll go ahead release this shortly.

Best, 
John

**Comment by quenousimporte** [comment]
Hi John, I tested in beta and was not able to reproduce, so I guess it's all good!
Thanks for your amazing job and reactivity 💃

**Comment by johnozbay** [comment]
You're so very welcome! Thank **_you_** for filing this! 🙏🏻

We pushed this live just now, and it should all be fixed!
–– and I think we broke the landspeed record for the fastest github-issue bugfix 🎉 haha

Thanks a million for filing this once again! 
Please keep 'em bugs coming!
