### ISSUE TITLE
[Feature Request] HyperLinks to other documents 

### ISSUE THREAD

**Issue by NikoKS** [cryptee/web-client#127]
First of all, great job on the app! it truly is beautiful in my opinion.

I have a feature request that would make the document a whole lot more useful.

Would it be possible to make hyperlinks able to open other documents? This would make the document kind of like a wiki. This would be really helpful when creating a larger knowledge base where many documents are related to one and another.

as a side request, how likely is it to be able to implement [mermaid.js](https://github.com/mermaid-js/mermaid) and markdown math equation within cryptee document editor? I think it would make it more towards a full-featured markdown editor.

**Comment by johnozbay** [comment]
Hi there,

This feature already exists.

You can read about how to link documents/files to your documents here on our helpdesk :
https://crypt.ee/help?article=how-can-i-link-attach-files-or-documents-to-documents

Best,
John

--- 
Also duplicate of #84.
