### ISSUE TITLE
[Feature] Add Draw.io Support

### ISSUE THREAD

**Issue by gjhklfdsa** [cryptee/web-client#13]
**Description** Add Draw.io Instance, preferably with the security and collaboration features of Cryptee.
**What is Draw.io**? Draw.io is a free software alternative to Google Draw.
URL: https://github.com/jgraph/drawio

**Comment by johnozbay** [comment]
Similar to #12! I love the idea, and it's a yes! 

I'll absolutely try to make it happen as fast as humanly possible. 
This would make a few users incredibly happy.

Will run do some feasibility research and keep this thread updated.

**Comment by johnozbay** [comment]
Looks like this is not going to happen, and we're looking into what it would take to build our own one instead for various reasons ✌🏻  Thanks a lot for this recommendation!
