### ISSUE TITLE
[Feature] Search for multiple tags

### ISSUE THREAD

**Issue by Parasrah** [cryptee/web-client#132]
**Is your feature request related to a problem? Please describe.**
I have many small documents, and want to be able to bring up a document based on the tags. I've been diligent in adding tags under the header of each document, but it seems I can only search for one tag at a time, which doesn't narrow down the results as much as I'd like

**Describe the solution you'd like**
Would be nice to be able to use something like a `#firsttag #secondtag` syntax to be able to narrow down search results using multiple tags (that aren't necessarily next to each other or in that order mind you)

**Comment by Parasrah** [comment]
I don't know what I searched for before creating this that I didn't see #60 but this is 100% a duplicate. Consider it another vote for the advanced search though, very excited for that

**Comment by johnozbay** [comment]
Thanks for discovering #60! 

When we switched to `v3` back in February, we ended up having to postpone this a liiittle bit, so that we can first fix `v3`'s bugs but this is coming _very_ very soon! Stay tuned over at #60!
