### ISSUE TITLE
[Bug] Keyboard flies away in new document dialog

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#134]
**Describe the bug**
This one is firmly in the “hard to reproduce” and “maybe iPadOS is just buggy” and “wtf?” categories. Sometimes (but not always), the on screen keyboard will fly up to the middle of the screen and have its layout screwed up when you try to create a new document and the cursor moves focus into that dialog.

**To Reproduce**
With lots of ??? because I don’t have a reliable repro yet:
1. Try to create a new Cryptee document by pressing the button on the sidebar.
2. Observe the keyboard madness and inability to type or close the keyboard.

**Expected behavior**
Keyboard stays where the keyboard should be!

**Screenshots**
![IMG_0058](https://user-images.githubusercontent.com/273696/126019035-d2338168-1341-457e-ad65-189403fffa5f.png)

**System Information (please complete the following information):**
 - Device: iPad Pro 11 (3rd gen)
 - OS: iPadOS 14.6
 - Browser: Safari PWA

**Comment by dhda** [comment]
I’ve been having a lot of on-screen keyboard issues with Cryptee PWA on iPad, actually. Frequently (probably most of the time), I can’t get the keyboard to open when I select the “encryption key” text field on start up, for example (so I can’t log in unless I go out to my password manager, copy my key from there, and paste it in the field). And then even after logging in there’s just no keyboard (device orientation doesn’t change it, nor does split view or slide over).

Restarting Cryptee doesn’t help. Reinstalling the PWA doesn’t help. Restarting the iPad does fix it (until it stops working again sometime later).

Not having a keyboard at all also makes it hard to reproduce the messed up keyboard 😆

Plausibly these are related? I should probably expand this into an “iPad keyboard issues” ticket.

**Comment by johnozbay** [comment]
Hi there! Thanks for filing this! 

Fucking apple 🤦🏻‍♂️ here we go again – this is a famous, old PWA keyboard bug. 
Apple has been fixing - breaking - fixing - breaking this for ages now. All the way back from iOS 12. 
You can see screenshots here : 
https://medium.com/@firt/whats-new-on-ios-12-2-for-progressive-web-apps-75c348f8e945#70c9

I'll dig up the old webkit bug we filed and ping it again. 🤦🏻‍♂️

– also if keyboard doesn't appear at all, it may also be related to this : 
https://bugs.webkit.org/show_bug.cgi?id=211018

Am considering having a dedicated iOS PWA Quirks / Bugs thread to document all these for future referencing. 
It's insane how many things Apple fixes and breaks again 2 years later.

**Comment by johnozbay** [comment]
Hi there, 

This was an iOS bug, and we can't seem to reproduce this on iOS 15 anymore. Closed it with https://github.com/cryptee/web-client/commit/13fec562257ea35b3fec08d5b3a9ec180e457f78 – but please feel free to re-open and keep me posted if this comes up again, and I'll ping our friends over at apple. 

Thanks,
J
