### ISSUE TITLE
[Bug] Some markdown shortcuts stopped working

### ISSUE THREAD

**Issue by arturolinares** [cryptee/web-client#139]
**Describe the bug**
Some markdown shortcuts stopped working. So far, I've found these: Headers, quotes and dividers. They all have in common that the shortcut starts as the first character followed by a space.

**To Reproduce**
1. Open a document
2. Type `#` followed by a space.
3. Write the header
4. The line doesn't have the expected format. The same happens with quotes (`>`) and the divider shortcut (`---`)

**Expected behavior**
The markdown character is removed (`#`, `>` or `---`) and the line gets the expected format of a header, quotation or divider accordingly.

**Screenshots**

https://user-images.githubusercontent.com/203078/142085099-834cae80-876f-44ac-bc5d-fed9a76645ae.mp4

**System Information (please complete the following information):**
 - Device: Laptop
 - OS: Linux
 - Browser: Chrome
 - Browser Version: Latest
 - Browser Extensions / Add-ons / Content/Ad-Blockers: None
 - Do you have any DNS-based content/ad-blockers? None 
 - Are you on a managed network? No

**Additional context**

**Comment by johnozbay** [comment]
Hey Arturo! 

Thanks a million for spotting & reaching out with this!
This one's on us. We made a logic error while trying to fix #137, and our automated tests didn't catch it either. 

We fixed this & released an update about a minute ago 
+ Updating our automated tests now as we speak to make sure we catch these before they happen next time.

**Comment by johnozbay** [comment]
Thanks again for all these! Please keep em bugs coming! 🕷
We'll get them squashed right away
