### ISSUE TITLE
[Feature Request] Add Vim Keys to Document editor

### ISSUE THREAD

**Issue by pragmaticmero** [cryptee/web-client#149]
**Is your feature request related to a problem? Please describe.**

- I've used obsidian in the past, and it has the option to use vim keys in a very clever way, I and a lot of people are accustomed to use Vim keys. Can you add that functionality in crypt.ee?

**Describe the solution you'd like**

- Add a Vim key option (turned off by default) for cryptee docs.

**Additional context**

- Mimic Obsidian's Vim key style

**Comment by johnozbay** [comment]
Hi there! 👋🏻
Thanks for filing this. 
Cryptee Documents is, as its name implies, a rich document editor, much like Google Docs, Pages, Words, etc, and its intended audience are not developers, nor is its current audience developers. It's built for everyone to have an easy to use safe home for their documents (incl. people like our parents, grandparents etc) and that's what we're building the service towards.

Therefore we will not be adding vim hotkeys or shortcuts to Cryptee Docs, as it's not a good demographic or product fit (for the very same reason it wouldn't exist on Google Docs, Word etc.), it will simply take away from its minimalist ethos, and complicate it unnecessarily. 

Hoping this makes sense ✌🏻

Best,

John
