### ISSUE TITLE
[Bug] Font Selector Closes Itself When Selected Text Runs Off Screen

### ISSUE THREAD

**Issue by elevatorz89** [cryptee/web-client#150]
**Describe the bug**
When you select enough text so that it goes off the bottom of the screen, the font selector refuses to stay open. For any amount of text that is visible without scrolling, the selector works fine.

This bug seems to only affect desktop browsers (including the PWA version). On mobile, the bug doesn't occur.

**To Reproduce**
1. Select an amount of text that goes off the bottom of the screen, to the point where scrolling is required to see it all.
2. Attempt to open the font selector.
3. Observe the font selector instantly close on you.

**Expected behavior**
The font selector should stay open and allow me to edit the text as normal.

**Video**

https://user-images.githubusercontent.com/53919102/166172420-d0cf6375-4dcd-4529-b17b-c614a680c624.mp4

**System Information (please complete the following information):**
 - Device: [Custom Built PC, ask for specs if necessary]
 - OS: [Windows 10]
 - Browser [Firefox, Vivaldi]
 - Browser Version [Firefox 100 / Vivaldi 5.2.2623.41 (Stable channel) (64-bit)]
 - Browser Extensions: 
Firefox - "Open Multiple URLs", OneTab, Ublock Origin, "Export Cookies"
Vivaldi - Bitwarden, Ublock Origin, Dark Reader
 - Do you have any DNS-based content/ad-blockers? No.
 - Are you on a managed network? No.

**Comment by johnozbay** [comment]
Thanks a million for reporting this! 🙏🏻

I can confirm that we can reproduce this bug. We've updated our automated tests with much taller documents now, and now working on a fix as we speak. 

We'll try to release a hot-fix shortly within the day. Stay tuned 👍🏻

Best,
J

**Comment by johnozbay** [comment]
Hi there we've hot-fixed this and pushed out the update just now, and the update is rolling out as we speak and you should have the fix shortly. 

Thanks to this we've actually discovered 9 other similar bugs in nature with other features of the editor and fixed those as well. (i.e. using keyboard shortcuts to indent was causing a similar jump) also thanks to this we've discovered something that can give us a major performance boost with pretty much all inline-styled editor functions. 

We're starting to work on these perf boosts + changes now and hope to have it out with the upcoming version. 

Thank you thank you thank you for reporting this! 🙏🏻  Deeply appreciate your continued support, patience and help with everything related to Cryptee! We and our users owe you a lot! 

Best,
J
