### ISSUE TITLE
[Change] Distance between the text and the writing area

### ISSUE THREAD

**Issue by bryn1u** [cryptee/web-client#151]
Hey, 

First, i would like to thanks for your great and hard work on this project. It's really cool.
I want to move from Evernote to Cryptee with team but i have a few question which make me a little bit dissatisfied

Is it possible to:
1) increase the area of writing so that more text can fit on one line? (1 on screen)
2) reduce the distance between text after enter using? Don't you think that distance is too long? (2 on screen)
3) reduce the distance between bullet text? Don't you think that the distance is too wide (3 on screen)

![cryptee](https://user-images.githubusercontent.com/3471772/166334496-99c00d34-bc8b-4b05-ba24-f3b8b9019146.jpeg)

Some time age i asked you about some feature like evernote cliper has. Is it possible to do something similar for Cryptee?

Thank you,
Best regards,

**Comment by johnozbay** [comment]
Hi there, 
Glad to hear you're liking Cryptee. 

I've responded to you in another thread in #147 about (1) & (2). Please don't create duplicates. 
(3) has to do with line-height and you can change it in the editor. 

Hoping this helps,

Best,
