### ISSUE TITLE
[Question] How you keep safe encryption key???

### ISSUE THREAD

**Issue by mohitxskull** [cryptee/web-client#152]
can an attacker steal the encryption key from the browser ??

**Comment by johnozbay** [comment]
Hi there, your question is incredibly general and vague, and I'm not entirely sure how it's relevant to the project's repository. 
So I can only answer this generally. 

a) Your encryption key is **not** _stored_ in the browser, it's only kept in memory during your session.

b) You can optionally choose to store / persist your key in the browser between sessions for convenience by clicking the "remember key" button. But in this case the question is not about Cryptee, but about your personal threat model, and how someone may compromise your device / browser directly.

I strongly recommend studying, exercising and coming up with a personal threat model. Once you have a clear personal threat model, I recommend checking out our [threat model](https://crypt.ee/threat-model), where we discuss in detail, what Cryptee can and can't protect you from.

Best,

J

**Comment by highRisk1** [comment]
I am sorry sir for the inconvenience!

thing is that I am building a project for my resume and it's the same as crypt.ee,
I had already gone through the web-client code base but I was not able to find what I wanted.
so, sir, I wanna know how I can keep encryption keys safe without sending them to the server and also use them to decrypt user data.

[my project](https://seagoat.vercel.app)
[my project key generation](https://seagoat.vercel.app/dev)

what I am doing is generating a random long string (RLS) and generating key pair and using RLS as a password to protect the private key then using pbkdf2 to make the encryption key (EK) longer and then using that "long EK" to encrypt that RLS and at last storing that Encrypted RLS, the private and public key to my database.

Sorry one more time sir, for copying so many things from your website.

thank you, sir
