### ISSUE TITLE
More bashing silicon valley douchebaggery

### ISSUE THREAD

**Issue by anoncam** [cryptee/web-client#153]
**Is your feature request related to a problem? Please describe.**
Problem: Silicon Valley is the root of all that is wrong regarding the economics of software.  They are filth, and more ridicule feels good to me.

**Describe the solution you'd like**
I really need a lot more of [this](https://github.com/cryptee/web-client#:~:text=Did%20you%20feel%20that%3F%20All%20of%20Silicon%20Valley%20just%20shuddered%20in%20disgust.)

**Additional context**
Fucking fantastic readme.

**Comment by anoncam** [comment]
cant get chrome highlight link to be preserved in markdown link syntax.  bug for another repo: https://github.com/cryptee/web-client#:~:text=Did%20you%20feel%20that%3F%20All%20of%20Silicon%20Valley%20just%20shuddered%20in%20disgust.

**Comment by anoncam** [comment]
`https://github.com/cryptee/web-client#:~:text=Did%20you%20feel%20that%3F%20All%20of%20Silicon%20Valley%20just%20shuddered%20in%20disgust.`

**Comment by anoncam** [comment]
![image](https://user-images.githubusercontent.com/46797044/175644829-f7d942e9-9f41-4fe6-a69c-06a86a85137a.png)

**Comment by johnozbay** [comment]
Hahahahah this made my day! Glad you like the readme Cameron! ✌🏻

We'll be sure to add more SV-bashing easter eggs to the platform in the near future. 

Best, 
J

**Comment by anoncam** [comment]
For this, I just signed up for cryptee let me see what i end up using 2TB for ;)
