### ISSUE TITLE
[Bug] Mobile Landing Page Visual Issues

### ISSUE THREAD

**Issue by elevatorz89** [cryptee/web-client#155]
**Describe the bug**
The mobile landing page has odd formatting/size issues, and both appear to be different based on the browser you're using. In Firefox, the cryptee logo doesn't completely line up with the navbar when you scroll down. In Chrome, the "A Private Home For All Your Digital Belongings" text looks like the screenshot shown below.

**To Reproduce**
1. Visit https://crypt.ee on a mobile browser.
2. Observe.

**Expected behavior**
On Firefox, the cryptee logo should line up completely with the navigation bar. In Chrome, the text shouldn't be wrapped to the left side to the point where there's one letter per line.

**Screenshots**

Firefox 
![Screenshot_20220730-123005_Firefox](https://user-images.githubusercontent.com/53919102/181928074-f205ef0d-9a0b-49ee-8054-a0e5a01f7300.png)

Chrome
![Screenshot_20220730-122115_Chrome](https://user-images.githubusercontent.com/53919102/181929304-9e2b6192-c7ce-46ce-a1ae-da320444bb15.png)

**System Info**
Firefox Version:
103.1.0 (Build #2015892987)

Firefox Extensions: uBlock Origin, Dark Reader

Chrome Version:
Chrome 103.0.5060.129

Device: 
Galaxy S10 SM-G973U
Android 12 

No DNS content blockers
No VPN

**Comment by johnozbay** [comment]
Hi there! Thanks a lot for filing this so quickly! 

If possible could you please check to see if it's fixed after you reload a bunch of times / once you clear the cache? 

Looking at the screenshots, and knowing how we laid out the grid in CSS, I'm somewhat convinced that this is an old cache of the CSS file displaying the new HTML file somehow. 

We'll shortly cache-bust from the servers as well just in case if someone else is having similar issues!

**Comment by johnozbay** [comment]
—— Currently the servers are taking in heaving traffic due to the update, so we're going to bust the cache as soon as there's a room to breathe for 10 seconds haha

**Comment by elevatorz89** [comment]
The problem seems to be fixed on the chrome side, but Firefox still has the problem with the logo.

**Comment by johnozbay** [comment]
Hi there! 

We've just released an update with a few small bugfixes, including one for this one! 

We tested on both Win, Mac and Android Firefox , and it seems to be fixed now! Give it a try and let us know if you're still experiencing any issues!

Best,
J

**Comment by elevatorz89** [comment]
It seems that the issue on Firefox still persists, even after erasing my cache.

![Screenshot_20220801-191638_Firefox](https://user-images.githubusercontent.com/53919102/182260942-6a5a8493-5727-4c73-aa62-b8c065ddea94.png)
