### ISSUE TITLE
[Feature] Add support for some kind of chart file

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#159]
**Is your feature request related to a problem? Please describe.**

Current Markdown chart support isn't that great honestly.

**Describe the solution you'd like**

I would like some dedicated chart file support like .csv or similar. Even an own format would be great. One needed feature I would highlight is cell formatting such as fill coloring additionally to all the other basic features.

**Additional context**

**Comment by johnozbay** [comment]
Hi there,

This feature is being tracked in #64! 
Closing since it's a duplicate!
