### ISSUE TITLE
[Bug] Setting cursor to URLs in checklist and thus opening them is buggy

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#161]
**Important Note**
_If you have any account-specific issues, like having problems signing-in, resetting your password, or issues related to your payments etc, you should first contact our [helpdesk](https://crypt.ee/help). We use Github to track issues affecting all users / bugs with the apps or service, and due to the fact that we can't exchange account-specific information on Github, our Helpdesk is much better equipped to handle account related issues._

**Describe the bug**

I have a set of URLs that I can click on and put the cursor in so the open link popup can appear above and I can click on that to open the link. If I make a todo list of these URLs the selecting part for a popup to appear doesn't work as great. Sometimes the cursor aren't placed in the URL and I have to long press it. Overall really weird.

**To Reproduce**
1. Select URLs
2. Make them a todo list
3. Try clicking on them
4. Sometimes it is really sloppy/doesn't work

**Expected behavior**

Cursor can be placed inside.

**Screenshots**

**System Information (please complete the following information):**
 - Device: [e.g. iPhone6 / Laptop with touchscreen etc.] Samsung Galaxy
 - OS: [e.g. iOS8.1, Windows 10] Android 12
 - Browser [e.g. safari, chrome, firefox, stock browser] Bromite
 - Browser Version [e.g. 22] 103.0.5060.140
 - Browser Extensions / Add-ons / Content/Ad-Blockers [e.g. uBlock Origin, CanvasBlocker etc. on iOS you can check these from your settings > safari > content blockers.] Default Bromite adblocker
 - Do you have any DNS-based content/ad-blockers? [i.e. pi-hole] No
 - Are you on a managed network? [e.g. VPN / Corporate / Campus Network] N/A

**Additional context**

**Comment by johnozbay** [comment]
Hi there! 👋🏻

I think this might actually be related to #162! Once we know a bit more about this, let's get back to this and take a look at both! Thanks a lot for filing these! Deeply appreciate it!
