### ISSUE TITLE
[Question] Page break

### ISSUE THREAD

**Issue by shawn1thompson** [cryptee/web-client#164]
Not sure if this is a bug or me not knowing how, but how can I remove a page break? I inadvertently inserted one trying to figure out how to enter text after a table and now I can't figure out how to remove it. Thanks.

**Comment by johnozbay** [comment]
Hi there 👋🏻

For future, we recommend reaching out for questions like this via our customer support, as posting here will take engineering time (vs customer support time) to answer these types of inquires. — and we're a tiny company so we're trying to be mindful of our resources as much as possible 😅🙏🏻

To answer your question I'll need to know a few things. i.e. whether if you're in continuous editing mode or in pdf / paper / print editing mode? 

In general you can delete page-breaks by pressing backspace a couple times until you're in the previous page OR by selecting the page break like you're selecting text with your cursor and pressing delete. 

https://user-images.githubusercontent.com/611338/185780657-7cdb2248-c13d-470d-ade0-be9273163468.mov

Hoping this makes sense and helps,

Best,

J
