### ISSUE TITLE
[Feature Request] Highlight album name in the input when change-album-name popup opens

### ISSUE THREAD

**Issue by pablo03v** [cryptee/web-client#176]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to click the box to enter the new album name.

**Describe the solution you'd like**
Automatically highlight the text in the popup so it can be replaced by the new string the user's about to enter.
https://github.com/cryptee/web-client/blob/b57f29eb3533f094aa35a4938f91acc63fb6c538/source/imports/app/photos-popup-album-info.kit#L5

**Additional context**
I would also appreciate if I could press enter to actually save the changes.
https://github.com/cryptee/web-client/blob/b57f29eb3533f094aa35a4938f91acc63fb6c538/source/imports/app/photos-popup-album-info.kit#L22

**Comment by pablo03v** [comment]
It's still an issue I am facing. The name field isn't focused to start writing the new name so the album is called 'NEW ALBUM'.

**Comment by johnozbay** [comment]
Hey @pabloscloud, thanks for being patient with this! 

Apologies for the delay, we didn't have this categorized properly internally in our tracker so we overlooked it. I'm pushing this to the top of our list both for photos and docs rename modals, and we'll have this updated in the upcoming release! 

Stay tuned for the next update, and it will be out 👍🏻

Thanks!

**Comment by pablo03v** [comment]
great. This will make the workflow so much easier imho

**Comment by johnozbay** [comment]
Hey @pabloscloud! 👋🏻

This is now fixed this in the alpha version and the issue is linked to our internal issue/release tracker.
Once the update with this fix is out (should be in a few mins), this issue will be closed automatically, and you'll get a notification!

Thank you so much for filing this, your help and patience! 🙏🏻

**Comment by pablo03v** [comment]
Awesome!!! Love developers who actually care
