### ISSUE TITLE
[Change] Bring Heading Toggle back out

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#181]
It's very common that I use the heading feature in notes. It used to be a heading button next to Bold etc but then was moved into the 'Aa' menu.
This makes for more steps/clicks to getting a heading. 

**Describe the solution you'd like**
I think keep the heading buttons in that menu but also add a heading button outside the menu next to Bold etc. Difference being, it would be one button but as you press it, it changes between H1 H2 and H3.
This would make for a quicker way to cycle through heading types while maintaining an efficient use of space (good UI). 
If it helps you could also group list types this way.

1st prize would be allowing the user to customize the UI / order of their formatting buttons. 

I know the ## markdown typing is an option but sometimes it's just nice to use the mouse to fix formatting after typing.

**Comment by johnozbay** [comment]
Hi there! 

As you mentioned in the past H1, H2 and H3 as well as a bunch of other buttons like font sizes and the font name were separate buttons. We had to consolidate these to fit more features into the top bar. 

In addition, their current placement is actually no different than any other rich document editor such as Google Docs or Apple Pages, both of which use a dropdown for headings. 

I'm afraid we won't be able to change this.

**Comment by S7venLights** [comment]
Oh dear sorry I hadn't noted down what issues I have reported from my list sorry. 
I suppose the button cycling through heading styles button idea is not on cards either? 
No stress either way.
