### ISSUE TITLE
[Bug] Copy pasting HTML from Cryptee in Dark Mode into email results in white text

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#182]
**Describe the bug**
Not technically a bug but maybe there's a solution to the problem none the less: 

Copy pasting into HTML email thread from cryptee running in dark mode results in invizible emails. Probably because the text is copied as having a white colour and then is not visible against a white background. 

 

**To Reproduce**
1. Use Cryptee in. dark mode
2. Copy text into email (in my case Tutanota in dark mode)
3. the text is visible during drafting but once sent it isn't. 
4. Using Cntrl shift V avoids the issue but there may be a better solution. 

Perhaps if the text copied had automatic as its colour setting rather than white, then this would be avoided. 

**System Information (please complete the following information):**
 - Device: [e.g. Browser Chromium into Tutanota on Firefox]
 - OS: [Linux]

**Comment by johnozbay** [comment]
Hi there! 

This actually has to do with your operating system, browser and destination app combination, but not about Cryptee. 

In general, when you select text in Cryptee, it's no different than selecting any other text in your browser. If your os / browser / destination app chooses to use the rich formatting, it will carry over, if not — you'll paste unformatted text. 

To work around this issue you can use your OS's built in paste without styling shortcut (i.e. ctrl/cmd + shift + v)

Hoping this helps,

Best,

**Comment by S7venLights** [comment]
Yes thanks I know about - Ctrl shift v

How about this idea: Perhaps if the text copied had automatic as its colour setting rather than white, then this would be avoided.

**Comment by johnozbay** [comment]
Cryptee actually cannot detect when you copy a text. It can only detect when you paste something. The rest is handled by the browser and OS. So I'm afraid we wouldn't be able to style text to auto then revert back during the copy/paste event, as that's handled entirely by the browser and OS themselves. 
Hoping this makes sense ✌🏻 
Sorry, I wish we could make this better 😞
