### ISSUE TITLE
[Feature] Allow Cryptee to work with Tor Browser

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#183]
I use Tor system wide on my phone but have to exclude crypt.ee from tor in order to use it. Can't sign in with Tor network. 
Is there a reason for this?

**Comment by johnozbay** [comment]
Hi there 👋🏻

Thanks a lot for filing issues and helping us improve Cryptee! 

First off — I noticed that you've opened a bunch of new issues without following our issue template. 
Neither have you tagged / labeled them correctly. As a small team, we would deeply appreciate if you would put a bit more  care into opening github issues.

Secondly, some of the issues you wrote about, we actually have dedicated helpdesk articles talking about them in detail, like this issue for example.

https://crypt.ee/help?article=why-doesnt-cryptee-work-with-tor-browser-or-firefox-incognito-private-mode 

Take a look, and if the lack of this feature in Firefox / Tor is bothering you, please leave a comment on their bug tracker. As it would help the team at Mozilla gauge the interest in this better. ✌🏻

John

**Comment by S7venLights** [comment]
Right thanks, I was typing on a phone, I can tidy them up in the morning :)
