### ISSUE TITLE
[Bug] Updating browser results in having to re-enter encryption key

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#184]
**Describe the bug**
I update brave browser from Github, it has fairlty frequent updates. Fairly often the Brave updates seem to cause Cryptee to forget the encryption key. 
This can be annoying when you need to make a quick note and you open your note only to find you have to open your password manager to access anything. 

**System Information (please complete the following information):**
 - Device: Happens on two of my android phones
 - OS: Android 7&12
 - Browser: Brave Browser
 - Browser Version [latest]
 - Browser Extensions / Add-ons / Content/Ad-Blockers:  none of these settings are on, not even Braves built in settings

**Additional context**
Doesn't happen on PC and I can't use any other Chroium based browser, Bromite causes issues with Cryptee, and Brave is the only private browser that has good PWA support on android.

**Comment by johnozbay** [comment]
Hi there, 

This is a browser specific issue, and an issue specific to how you update your browser. When you update the browser via Github (or any other place manually vs app store etc), you're effectively re-installing (overwriting) the browser on your device, and it may result in all locally stored things getting wiped.

This is not an issue with any other Chromium browser (i.e. Google Chrome, Samsung Browser, Edge etc neither on desktop nor on mobile) 

I'm afraid this has nothing to do with Cryptee and has everything to do with how and where your browser of choice stores things locally.  

Hoping this helps,

Best,

J

**Comment by S7venLights** [comment]
Update, despite my update methods not changing this issue seems to be resolved
