### ISSUE TITLE
[Bug] PWA stuck in offline mode on Brave (Android)

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#185]
**Describe the bug**
Sometimes my PWA gets stuck in offline mode and the only thing that releases it is opening the host browser and opening Cryptee in the browser. 

**System Information (please complete the following information):**
 - Device: Happens on two of my android phones
 - OS: Android 7&12
 - Browser: Brave Browser
 - Browser Version [latest off Gthub updates often]
 - Browser Extensions / Add-ons / Content/Ad-Blockers: Edit:  [Had braves default standard tarcker and fingerprint settings on, have now disabled and will keep testing]
 - Do you have any DNS-based content/ad-blockers? Not sure, I use random DNSCrypt servers changes automatically 4of10 have filtering. 
 - Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there! 

Cryptee and its PWA utilizes your browser's built in connection reporting api called [navigator.online](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)

https://github.com/cryptee/web-client/blob/f487c37cd4bb7d2df62f490d6cd0f24ff1286cf4/source/js/docs.js#L473

And once Cryptee switches to offline mode, it keeps checking this value (and pings our servers to see if it can connect) and when it can, it disables the offline mode. 

In short, the issue you're experiencing either have to do with : 
— your browser and their implementation of connectivity reporting, 
— your OS and how that reports connectivity to the browser. 
or
— your extensions / dns-servers / content-blockers etc interfering with the connection and causing mis-reporting issues. 

I'd strongly recommend testing things out in other browsers first, as chances are (judging by your other github issues your browser installation is a rather unique one) most of your issues related to Cryptee will go away once you start using another browser (or use another installation method). 

Hoping this helps,

J

**Comment by johnozbay** [comment]
If you (or others) continue to experience issues related to the offline mode, first take a look at our article here to debug other factors that contribute to connectivity issues : 

https://crypt.ee/help?article=im-having-trouble-logging-in

And if you still continue to experience these types of issues, leave a comment below, and with more information we can get to the bottom of these types of issues faster, since connectivity issues (and real-life network conditions) are so incredibly hard to simulate and test against in-house.

**Comment by S7venLights** [comment]
I've updated the issue info, made some changes to Brave Browser and will continue to test and report back if it happens again.

**Comment by S7venLights** [comment]
Confirmed issue was caused by Brave Androids adblocker. Solution Turn off fingerprint and tracker protections for Cryptee.
