### ISSUE TITLE
[Change] New Doc button placement (I often press this by mistake instead of the dropdown dots of documents)

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#186]
I use cryptee with the side menu pinned open.
The new doc button is often very near the ⋮ button of a note, and I often press this by mistake. Perhaps a slightly bigger gap would help.

**Comment by johnozbay** [comment]
Hi there,

I'm not sure if there's a better logical place to put this button, but it would require an entire re-design of the platform and editor in general to pull this off, and at the moment we don't have the resources to address this issue.

My apologies,

John

**Comment by S7venLights** [comment]
No stress, I didn't think an entire re-design would be Necessary, I thought it would just be changing the spacing between the two with a slight change of the ⋮ button position.

**Comment by johnozbay** [comment]
I wish we could do this easily hahah how I would love to make updates to the left sidebar. 

Basically, everything is somewhat connected. For example the side-by-side split in #179 is actually related to this even. If you pin the sidebar or when the sidebar opens, the amount of space available affects what should be visible in the editor (as well as the tools) it also affects Cryptee's built in pdf viewer's side-by-side (or picture-in-picture) sizing, as well as things like right click dropdown menus that appear in the documents list and their positioning. Even our PDF rendering engine for the document takes a look at your window's width / height, calculates the available space for viewing and editing the document and shrinks/expands the document accordingly. 

So to make the sidebar bigger, we would have to touch pretty much every single one of these features. 😵
We could theoretically shrink the list's width to add more space, but then document names would take more lines, and it would also be impractical. What we're looking into actually is moving some of those action buttons (like new doc etc) inside the sidebar to make room for some upcoming features, and that might eventually solve this issue for you!

My apologies again! Wishing we could do some of these easier ✌🏻
