### ISSUE TITLE
[Bug] Selecting text with a mouse, then trying to change/append your selection (with the mouse) results in the drag and drop upload dialogue appearing

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#188]
**Describe the bug**
Selecting text with a mouse, then trying to change/append your selection (with the mouse) results in the drag and drop upload dialogue appearing, instead of just making a new selection.

OS: Fedora Kionite
Browser: Chromium
Browser Version 109.0.5414.119 (Official Build) (64-bit) off Flathub
Browser Extensions / Add-ons / Content/Ad-Blockers: Edit: Disabled
Do you have any DNS-based content/ad-blockers? Yes
Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there! 

If possible could you please post a screen-recording of this happening and details of your operating system and browser? Otherwise we can't reproduce this or fix this. And again, please follow our issue templates, and write about your OS, browser, extensions etc. we have these for a reason. 

Thanks.

**Comment by S7venLights** [comment]
Sorry, I only read your replies after posting all my feedback.

In my experience it has happened on various PC browsers, I'm on Fedora in ungoogled Cromium at the moment, but I can post a screen record if you cant replicate.

**Comment by S7venLights** [comment]
Screen record Video, on peertube: https://www.orion-hub.fr/w/i1AZxFWd11nmL5S858Ajre

Updated issue info

**Comment by S7venLights** [comment]
Since this issue is closed, How do I know if this issue has been seen?
no rush, just wondering.

**Comment by S7venLights** [comment]
Update, this issue still exists although it is minor, no rush. Also the screen record i sent before won't work as orionhub is defunct
