### ISSUE TITLE
[Bug] Encrypting & Saving Dialogue stuck on screen

### ISSUE THREAD

**Issue by S7venLights** [cryptee/web-client#189]
**Describe the bug**
Encrypting & Saving banner sometimes stays stuck on screen. Seems to happen when the device loses connection and regains it, cryptee shows as offline, I have to f5 refresh and apon refreshing offline notes sync, the banner appears but doesn't dissapear.

**To Reproduce**
1. Open Cryptee on one device and make a new note
2. Disconnect that device from the internet and leave it open
3. open Cryptee on another device and make a new note
4. Reconnect device 1 to internet (This is usually what triggers the bug)
5. F5 refresh can remove the bug

**System Information:**
 - Device: [Android 7&13 Cellphone in Brave Browser and Linux Laptop in [Chromium](https://www.chromium.org/Home) .]
 - OS: Fedora Kionite
 - Browser Version [Latest Brave mobile, 109.0.5414.119 (Official Build) (64-bit) Cromium Flatpak
 - Browser Extensions / Add-ons / Content/Ad-Blockers Braves inbuilt standard tracking and fingerprint Protection (Will test with it off)
 - Do you have any DNS-based content/ad-blockers? On PC yes
 - Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there, 

Could you please follow the issue templates and write out the OS, Browser, Extensions etc otherwise we cannot reproduce or fix bugs like these. Especially with issues related to connectivity issues, we'll need to know if something else like a browser extension or dns config etc tampering with your connectivity. I promise we have these fields for a reason.

Thanks.

**Comment by johnozbay** [comment]
This may possibly be related to #185 as well.

**Comment by S7venLights** [comment]
Roght this happens on all my devices without content blocker extensions and only my PC has a DNS with content blocking, So I don't think it's related.

According to the steps I provided you should be able to reproduce the issue?
If not, no stress, I'll do more testing when I have time.

**Comment by S7venLights** [comment]
Updated the info. I see I did have braves standard built in protection enabled, thought I had turned it all off. I've disabled it now and will test for a while.
The steps to reproduce the bug didn't cause the bug at first attempt now.
I will clean up the other issues posted in the coming days.
