### ISSUE TITLE
[Bug] Incorrect list format when exporting documents

### ISSUE THREAD

**Issue by ramonls8** [cryptee/web-client#200]
**Describe the bug**
When exporting documents to Markdown or HTML, unordered lists with different tabulations are not exported in the correct format. If an item is tabulated more than once, it is exported with two "\*" instead of a few spaces and only one "\*".

For example:
* example
  * example
    * example

Will be exported as:
```
* example
* * example
  * * example
```

Instead of:
```
* example
  * example
    * example
```

**To Reproduce**
1. Create a document and write an unordered list into it.
2. Export to Markdown or HTML and open the resulting file.

**Screenshots**
Cryptee original document:
![cryptee doc 2](https://github.com/cryptee/web-client/assets/96984958/86dd450f-c212-46ea-b0f9-090bc53a03c2)

Markdown exported file:
![markdown export 1](https://github.com/cryptee/web-client/assets/96984958/66a277fd-8981-4177-b7eb-454b61dc928b)

HTML exported file:
![html export 2](https://github.com/cryptee/web-client/assets/96984958/023e5822-fc09-4953-a688-615fd96ac472)

**Comment by johnozbay** [comment]
Hi there 👋🏻

Thanks a lot for spotting and filing this.

It seems to be a combination bug between our editor and the markdown exporter we use. We're actively working on a fix for this now, and hope to get this out with the upcoming release! 

I've linked this issue to our internal issue/release tracker.
Once the update with this fix is out (should be in the next update, but you never know), this issue will be closed automatically, and you'll get a notification!

Thank you so much for filing this, your help and patience!

**Comment by johnozbay** [comment]
Hi there 👋🏻

Stopping by to say we've identified and fixed this in the alpha version and it will be out with the next update. 
Both the HTML and the markdown exports will be (~should be~) correct.

Many thanks for the great examples and screenshots!

Thanks ✌🏻
