### ISSUE TITLE
[Question] How can I zoom in and out on a picture stored in PHOTOS on a Mac?

### ISSUE THREAD

**Issue by LinYuyang86** [cryptee/web-client#215]
How can I zoom in and out on pictures stored in PHOTOS on a Mac? I tried using the mouse wheel, but it didn't work, then I used the trackpad, and it was able to zoom in, but the information bar above the picture was also enlarged.
I don't know if this is a bug or a question.

**Comment by johnozbay** [comment]
Hi there! You can double click / double tap on the enlarged image to zoom in. It's built for mobile devices where the double-tap gesture zooms in. (at least it should, depending on if the browser / device isn't stealing that gesture for some other action, i.e. dictionary etc) 

Hoping this helps!
