### ISSUE TITLE
Decrypt the text

### ISSUE THREAD

**Issue by a13519** [cryptee/web-client#226]
Hi, I had used your web site 3 years ago to encrypt some text by plugin with Trezor hardware wallet, it works fine. Currently I want to decrypt the text but your web site is disappeared : https://cryptee.io/encrypt/text

Could you help to decrypt the text or head me the way to do so?

Thanks,
Song

**Comment by johnozbay** [comment]
Hi there 👋🏻

cryptee.io is/was a separate completely unrelated project, and has nothing to do with our project https://crypt.ee — aside from the fact that they decided to use the same name without googling if someone else is using it. 

We have nothing to do with virtual currencies, hardware wallets or trezor. 

Wishing you the best of luck in reaching out to the correct owners! ✌🏻
