### ISSUE TITLE
[Bug] Large Images Cannot Be Resized.

### ISSUE THREAD

**Issue by elevatorz89** [cryptee/web-client#23]
Heyo,
I've found images over a certain resolution (Over 1000x1000 as an example) are not able to be resized on the web without zooming out. On mobile, it's just plain impossible.

**Comment by johnozbay** [comment]
Hi there, 

If I'm understanding this correctly, you're talking about resizing an image that is larger than 1000x1000 in the Document itself is that correct? Like this : 

![Screen Shot 2019-08-20 at 11 41 12](https://user-images.githubusercontent.com/611338/63332044-8730f780-c33f-11e9-89f1-91d109596423.png)

The photo in the image is 2400px wide, 1500px tall. But it is scaled down to fit the full width of the document. So when you resize the image up, the maximum size of that image will be as wide as your document on that screen, and you should be able to resize it down to any size.

If you're not able to see the resize handles, then I'm going to need specific information like browser name & version, OS name & version, which extensions you have installed, if it's a corporate laptop or not with an IT software limiting certain features on your device etc. (for example some corporate IT softwares limit taking screenshots of screen, or disable reporting available fonts & window width to websites to prevent easy fingerprinting of their employees based on these criteria etc)

**Comment by elevatorz89** [comment]
I just inserted a image that was 1000x1000, and could not resize it without zooming out..
I'm using Firefox 68.0.2 (64-bit), and Windows 10 update 1809. The only extentions I have installed are Bitwarden, Privacy, Ublock (disabled for cryptee), and the Notion web clipper. This is my personal computer so no IT software should be on here.

**Comment by johnozbay** [comment]
I think I've figured this out!

Looks like this is happening with images that are "block" (and not "inline" – so not left aligned and not right aligned), taller than the editor height, when they're overflow the viewport height. 

And strangely, if you add a line of text before or after the block image, then first click on the text, and on the image afterwards, the resize handles show up. 

But if there are no lines of text before or after the image, or the same line where the image sits is selected, image-resize handles don't show up. 
 
Can you confirm this strange behavior as well? 

![dog-gif](https://media.giphy.com/media/UKkes2qN2T70s/giphy.gif)

**Comment by elevatorz89** [comment]
Resize handles never show up period, assuming the image is bigger than the editor/browser height. I am unable to reproduce the exact behavior you are.

**Comment by johnozbay** [comment]
Hi there! This should be fixed now! Give it a try and let me know!

**Comment by elevatorz89** [comment]
Yes, thank you! It's fixed!
