### ISSUE TITLE
[Feature] Multiple selection for a single action in cryptee docs

### ISSUE THREAD

**Issue by l-lin** [cryptee/web-client#24]
Currently, we can only perform an action to a single file in cryptee docs, e.g. move file or download file.

I don't know if it's technically challenging, but it will certainly improve the user experience.

**Comment by johnozbay** [comment]
Hi there, 

You can already do this. Unless I'm misunderstanding what you're asking for.

![image](https://user-images.githubusercontent.com/611338/63331324-1f2de180-c33e-11e9-9d49-4b402d7da9b1.png)

Let me know if this isn't what you're referring to or open a new request and I'll gladly take a look ✌🏻
– Perhaps this needs better documentation. I'll see what I can do.

**Comment by l-lin** [comment]
My bad, I didn't notice the **+** sign when the mouse is hovering the file icon :sweat_smile:

**Comment by johnozbay** [comment]
Haha no worries at all! I really should make this clearer. I might add a "select file" option in the right click dropdown on individual files to make this easier to discover. 

Glad to hear this addresses your needs though ✌🏻
