### ISSUE TITLE
[Feature] Download Album Button

### ISSUE THREAD

**Issue by hamburghammer** [cryptee/web-client#30]
The posability to download a hole photo album from the overview with one click without needing to select all photos inside of it.

**Comment by johnozbay** [comment]
Hi there! 
Thanks for filing this! 

Would you rather have this in the albums view? 
(for example next to the ghost or delete album button)
Or 
Inside the album?
(for example a "download album" button, next to the select all button)

Freundliche Grüße ✌🏻
John

**Comment by hamburghammer** [comment]
I would love to see both but the most interesting one is a button in the albums view, like you suggested next to the delete and ghost button.

Thx for your quick response

**Comment by paulhovey** [comment]
It seems like the "Select All" button on the albums page doesn't do anything currently - perhaps if the ability to select albums from that page is implemented, the select all button would have a use :)

**Comment by johnozbay** [comment]
@paulhovey I'm guessing you don't have any loose photos that aren't in albums. 👀
Basically, similar to Google Photos / Amazon Photos etc. Cryptee doesn't require you to put all your photos in albums. So you can quickly dump stuff to your home first, and organize them into albums later. 

So on Photos' home screen, you can have photos and albums side by side. 
The select all button selects only photos. (and not albums) That's the reason why the "select all" button is there. – that being said, it should only show up if there's at least one photo in the folder/home, looks like this is a bug, and I'll fix it up in the next release.  

@hamburghammer this will likely be a desktop-only feature at first, and I'll slowly add support for mobile as well. Would this be alright for your use case? 

Thanks ✌🏻

**Comment by paulhovey** [comment]
Oh!  I do have all my photos in albums.  Nevermind 😇

**Comment by hamburghammer** [comment]
@johnozbay yes it will fit perfectly thx

**Comment by johnozbay** [comment]
Boom. 🎉

@hamburghammer New version has an album download button. 
@paulhovey fixed the select all button bug. 

Thanks a lot both ✌🏻
