### ISSUE TITLE
Cannot upload multiple images on Android

### ISSUE THREAD

**Issue by PrabuddhaKumar** [cryptee/web-client#34]
**To Reproduce**
1. Install the PWA
2. Go to photos, enter the encryption key and click on a created album
3. Click the upload button to add new images
4. The prompt shows File upload and allows me to click a new image from the camera, or upload from the default file manager.
5. Select the files option, and try to select multiple images. It prevents selecting multiple images.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android 10
 - Browser: Mozilla Firefox 
 - Version 68.3

**Additional context**
Great app. I was trying to upload multiple images to an album, however, the PWA was only allowing uploading files one by one. On Firefox desktop however, this was not a problem as I was able to upload multiple images.

**Comment by johnozbay** [comment]
Please take a look at this helpdesk article. 
It's a Firefox bug Mozilla has been refusing to fix for almost 2 years now. 
https://crypt.ee/help?article=i-use-firefox-on-android-why-cant-i-select-multiple-files-or-photos-to-upload
