### ISSUE TITLE
[Feature] Sort folder contents by type

### ISSUE THREAD

**Issue by Visual-Notes** [cryptee/web-client#37]
Currently, within folders, all items are sorted equally - alphabetically or by time, regardless of item type. This creates confusion when there are many different items in a folder.  I think it would be useful if the items within a folder were basically ordered by type: i.e. first folders, then files, then pages:

Subfolder a
Subfolder b
Subfolder c
File a
File b
File c
Page a
Page b
Page c

What do you think?

**Comment by johnozbay** [comment]
This a fantastic idea! Going to try and make this possible with the next update. 

Two questions. 

**1) Sorting**
For files, would you prefer if it's "All non document-files" (jpg, pdf etc) grouped together like  and sorted alphabetically like : 

Subfolder a
Subfolder b
Subfolder c
File a.pdf
File b.jpg
File c.pdf
File d.jpg
File e.xls
Doc a.crypteedoc
Doc b.crypteedoc
Doc c.crypteedoc

OR everything grouped based on extensions/filetypes like :

Subfolder a
Subfolder b
Subfolder c
File a.pdf
File b.pdf
File c.pdf
Photo a.jpg
Photo b.jpg
Photo c.jpg
Doc a.crypteedoc
Doc b.crypteedoc
Doc c.crypteedoc

**2) Icon**
What would you say is a good sort icon to represent file extensions / types? 
For sorting based on recency/time, currently there's a clock icon. 
For filenames, there's an A-Z icon.

Thanks a lot for this!

**Comment by Visual-Notes** [comment]
Glad that you accept my suggestion!

I think your second choice is the best solution:
Subfolder a
Subfolder b
Subfolder c
file a.pdf
file b.pdf
file c.pdf
Photo a.jpg
Photo b.jpg
Photo c.jpg
Doc a.crypteedoc
Doc b.crypteedoc
Doc c.crypteedoc

Maybe also this kind of sorting:

Subfolder a
Subfolder b
Subfolder c
Doc a.crypteedoc
Doc b.crypteedoc
Doc c.crypteedoc
file a.pdf
file b.pdf
file c.pdf
Photo a.jpg
Photo b.jpg
Photo c.jpg

The second question is particularly difficult to answer because the icon must be very small and must apply to all file types. Also, the same icon is often used for documents and files, and in this case it should be possible to distinguish between them.

This icon could be used for documents:

![document_icon](https://user-images.githubusercontent.com/1451511/74831958-90167c00-5316-11ea-8590-f109b35942b6.png)

And this one for files:

![file_icon_01](https://user-images.githubusercontent.com/1451511/74832010-af150e00-5316-11ea-8272-4b179abb3a32.png)


Or maybe this one, but I don't think it can be downsized as much as necessary

![file_icon_02](https://user-images.githubusercontent.com/1451511/74832020-b3412b80-5316-11ea-8bf6-5fbc3df511ca.png)

**Comment by johnozbay** [comment]
Sounds good! I've added this to the to-do list! Going to try and add this in with the next update.

**Comment by johnozbay** [comment]
This is now ready, and will be shipped with the next update. For now I'm using a puzzle icon, and will keep thinking of a better alternative. (and will likely have some kind of AZ to it to indicate it's still sorting names, but based on extensions) – If the folder only has regular Cryptee documents, this becomes confusing (A-Z sorts twice basically, first based on filenames, second based on filenames among file-extensions)
 
Feel free to ping with suggestions. I've also considered using a [pie-chart](https://fontawesome.com/v4.7.0/icon/pie-chart) and [cubes](https://fontawesome.com/v4.7.0/icon/cubes), but they're too wide and looks odd. (Same goes for puzzle, but it's flat left-side fits better with the arrow.
 
<img width="301" alt="Screen Shot 2020-02-19 at 16 26 20" src="https://user-images.githubusercontent.com/611338/74843491-a7fcf880-5334-11ea-8779-71b2a4b3daf1.png">

<img width="303" alt="Screen Shot 2020-02-19 at 16 26 26" src="https://user-images.githubusercontent.com/611338/74843498-aaf7e900-5334-11ea-88fc-e7652bab9806.png">

**Comment by johnozbay** [comment]
One more update on this. Added some spacing and separators with extensions/filetypes to make it even easier to find the files you're looking for.
 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/611338/74853104-1e562680-5346-11ea-9ace-f803682181f6.png">

And needless to say the separators are only visible when sorted by filetype.

The icon is the only thing left bothering me. Will keep thinking.

**Comment by Visual-Notes** [comment]
That's great! The dividers are very effective, everything is very clear now, I really like that. 
I guess the last selected sort is saved per folder?

**Comment by johnozbay** [comment]
> I guess the last selected sort is saved per folder?

Correct! They [already] are. (If for some reason this isn't the case let me know. That would mean the subfolders update broke something)

**Comment by johnozbay** [comment]
Thanks folks! Added this with this month's update!
