### ISSUE TITLE
Support for better syntax highlighter in code blocks (Docs)

### ISSUE THREAD

**Issue by DSuveges** [cryptee/web-client#43]
In my opinion the syntax highlighting of the code blocks are not too sophisticated, and in many cases not syntactically correct either. I'm wondering if it would be possible to integrate a syntax highlighter eg. [highlight.js](https://highlightjs.org/). I feet it would seriously improve the usefulness of the service.

If you agree it is a reasonable feature to have, but you don't have capacity to address the issue if you give me some pointers how I could contribute I might find bandwidth to implement.

Thanks a lot for this otherwise amazing product!

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Thanks a lot for the kind words and compliments! 
Fun fact, we are already using highlight.js. 😅

https://github.com/cryptee/web-client/blob/ab1d4aefe96f03523e5f62b4895cd47872f5d5da/source/js/lib/highlight.min-9.12.0.js#L1

https://github.com/cryptee/web-client/blob/ab1d4aefe96f03523e5f62b4895cd47872f5d5da/source/docs.kit#L14

It's the syntax-module, installed as a part of the editor : 

https://github.com/cryptee/web-client/blob/ab1d4aefe96f03523e5f62b4895cd47872f5d5da/source/js/docs.js#L431-L433

That being said, if you're getting different/better results in a separate version/installation of highlight.js (vs the implementation in Cryptee) – let me know the exact lines you're testing with, and I'd be happy to take a look to see if it's a bug ✌🏻
