### ISSUE TITLE
[Feature] Multiple tag search

### ISSUE THREAD

**Issue by clarin1478** [cryptee/web-client#60]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I try to search with multiple tags.

**Describe the solution you'd like**
Search option with multiple tag filter.

Off-topic:

How do you organize the documents for that this doesn't become chaos in a few years when you have many documents.

TY <3

**Comment by johnozbay** [comment]
Hi there! 👋🏻

Thanks a lot for filing this! 
I'm happy to say this is already in the works and on the way! 🎉

We're working on a new search engine for Cryptee Docs. It will have a lot more advanced features like :

`!arts` will exclude all results that have "arts" in it. 
`^lock` will find all results that start with "lock"
`.js$` will find all results that end with ".js" 
`!.go$` will find items that do not end with ".go"
`'blue` will find results exactly matching "blue"
etc.

but also, we're adding in logical operators. white space will act as an `AND` operator, while a single pipe `|` character will act as an `OR` operator. 

So you'll be able to type the tags with spaces, like : "designer chairs" and find results containing both the `designer` and `chairs` tags.

Alternatively you'll be able to type "designer | furniture" and find results containing either `designer` or `furniture` tags. 

I can't comment on when exactly this will be out yet, but it's aaaalmost ready, and I think we can get this out with the next update! 

Hoping this makes sense and helps! 

All the very best ✌🏻
J

**Comment by johnozbay** [comment]
Oh and also : 

> How do you organize the documents for that this doesn't become chaos in a few years when you have many documents.

The best way is to use a combination of sub-folders, tags and archiving. 
I.e. I use a structure like : 

Projects [Folder]
–– Project 1 [Folder]
–––– PDFs [folder]
–––– Documents [folder]
––––––– A Document [document] + [tagged with a bunch of things]

–– Project 2 [Folder]
–– Project 3 [Folder]
...
–– Project 4 [Folder] [ archived ] 
(so it won't show up on the regular list anymore, but you can search for it, and un-archive and bring it back to be visible on the list if you wish)

In a way it's the same as how you'd try organize documents on your computer, but with a few additional nice-to-have-features like archiving & tagging to make better use of the limited screen-real-estate we have & deal with the [side effects of on-device encryption](https://crypt.ee/help?article=how-can-i-search-documents-for-their-text-content) when it comes to search. 

Hoping this helps! 

Best,
J

**Comment by johnozbay** [comment]
Hi there! I've got some great news! 

Today we've shipped a major update [b57f29e](https://github.com/cryptee/web-client/commit/b57f29eb3533f094aa35a4938f91acc63fb6c538) to our search engine for Cryptee Docs, and you can now perform lots of complex searches. Take a look at [our blog for more details](https://blog.crypt.ee/march-2022-updates/).

Closing this for now, but once you get a chance to play around, let us know what you think, and if we can improve things in any way! 

All the best,
J

**Comment by clarin1478** [comment]
Hello,

This is Awesome 🎉

TY for your Work

BR

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
