### ISSUE TITLE
[Bug] Rapidly creating new subfolders breaks the active session's in-memory parent/children folder structure

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#61]
**Describe the bug**

Then creating a lot of new folders rapidly whose folders disappear until you leave and open that folder again.

**To Reproduce**
1. Open a folder
2. Click on 'create new folder' semi-rapidly (about every 0.25-0.5 secs).
3. Wait for it to disappear.

**Expected behavior**
I expect the subfolders to not disappear.

**Screenshots**
![gif1](https://user-images.githubusercontent.com/49041398/81904579-fed04200-95b2-11ea-87f6-f77da49f3f2d.gif)

**System Information (please complete the following information):**
 - Device: Low end Desktop PC (Intel i5-3330 with iGPU )with a standard mouse and keyboard, no touch and an Android phone (Sony Xperia XZ (F8331))
 - OS: Windows 10 Pro 64-bit 1909, Android 6.0
 - Browser: Desktop: Firefox 76.0.1 (64-bit), Phone: Chrome 80
 - Browser Extensions / Add-ons / Content Blockers: Desktop: Enchanced Tracking Protection, Nextcloud Passwords, uBlock Origin, Privacy Badger, HTTPS Everywhere, Decentraleyes, Multi-Account Containers (only use it for Facebook, Google, Reddit, Twitter) Android: none
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No

**Additional context**
Just noticed that this also happens (and on Android too) (can be fixed by just reloading the page):
![gif0](https://user-images.githubusercontent.com/49041398/81905527-5ae79600-95b4-11ea-9e71-c58c7d8ebd9e.gif)

**Comment by johnozbay** [comment]
Hi again! 👋🏻

Thank you so much for filing this bug & the screen recordings! 🙏🏻 
Looks like while introducing sub-folders ( #2 ) I've missed one tiny edge-case! – and that caused a chain reaction and broke a few things if one were to click new subfolder button too quickly. 

I've fixed this in the upcoming release, and it will be out in a few days with the upcoming update!

Our bug tracker will automatically close this issue when the new version is out, and you should get a notification from github! Needless to say, please do let me know if it's not fixed / fixed partially / incorrectly and I'll get it all fixed up ✌🏻

All the best,
J
