### ISSUE TITLE
[Bug] Subfolders are sorted incorrectly in the move modal

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#62]
**Describe the bug**
The side panel and the file move dialog doesn't have the same layout of the folder.

**To Reproduce**
1. Go to inside a folder.
2. Go to that folder inside the file move dialog.

**Expected behavior**
I expect the contents of the folder to appear in a exact same order inside the panel and the file move dialog.

**Screenshots**
![Screenshot (329)](https://user-images.githubusercontent.com/49041398/81906831-620fa380-95b6-11ea-9804-b1e5f05a29dc.png)
'zTEST0' is at the bottom of the folder.
![Screenshot (330)](https://user-images.githubusercontent.com/49041398/81906834-63d96700-95b6-11ea-8071-86503a305db3.png)
'zTEST0' is now not at the bottom.

**System Information (please complete the following information):**
 - Device: Low end Desktop PC (Intel i5-3330 with iGPU) with a standard mouse and keyboard, no touch and an Android phone (Sony Xperia XZ (F8331))
 - OS: Windows 10 Pro 64-bit 1909, Android 6.0
 - Browser: Desktop: Firefox 76.0.1 (64-bit), Phone: Chrome 80
 - Browser Extensions / Add-ons / Content Blockers: Desktop: Enchanced Tracking Protection, Nextcloud Passwords, uBlock Origin, Privacy Badger, HTTPS Everywhere, Decentraleyes, Multi-Account Containers (only use it for Facebook, Google, Reddit, Twitter) Android: none
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi again! 👋🏻 

Thanks a lot for filing this bug & the screen-grabs! 🙏🏻
I've fixed this in the upcoming release, and it will be out in a few days with the upcoming update! 

Our bug tracker will automatically close this issue when the new version is out, and you should get a notification from github! Needless to say, please do let me know if it's not fixed / fixed partially / incorrectly and I'll get it all fixed up✌🏻

All the best,
J
