### ISSUE TITLE
[Bug] Move modal scrolls unnecessarily with subfolders

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#63]
**Describe the bug**
Then trying to move a file or a couple of files inside a subfolder the file move diagol just jumps back to the parent folders top making it difficult to move files.

**To Reproduce**
1. Select a file (could be more than one file) and/or a folder (could also be more than one).
2. Click on 'move to'
3. Scroll down to any folder inside a folder.
4. Select it.

**Expected behavior**
I expect the folder chooser dialog to not move, just like then selecting a parent folder.

**Screenshots**
![gif](https://user-images.githubusercontent.com/49041398/81907911-0219fc80-95b8-11ea-808c-ba3a5656ef73.gif)

**System Information (please complete the following information):**
 - Device: Low end Desktop PC (Intel i5-3330 with iGPU) with a standard mouse and keyboard, no touch and an Android phone (Sony Xperia XZ (F8331))
 - OS: Windows 10 Pro 64-bit 1909, Android 6.0
 - Browser: Desktop: Firefox 76.0.1 (64-bit), Phone: Chrome 80
 - Browser Extensions / Add-ons / Content Blockers: Desktop: Enchanced Tracking Protection, Nextcloud Passwords, uBlock Origin, Privacy Badger, HTTPS Everywhere, Decentraleyes, Multi-Account Containers (only use it for Facebook, Google, Reddit, Twitter) Android: none
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No

**Additional context**
This moving files a bit more difficult and frustrating especially then theses a lot of folders.

**Comment by johnozbay** [comment]
Hi there! 
Many million thanks for filing this & the screen-recording! 🙏🏻
I've fixed this in the upcoming release, and it will be out in a few days with the upcoming update! 

Our bug tracker will automatically close this issue when the new version is out, and you should get a notification from github! Needless to say, please do let me know if it's not fixed / fixed partially / incorrectly and I'll get it all fixed up✌🏻

All the best,
J
