### ISSUE TITLE
[Bug] Ghost Album "confirm" button not resetting when used consecutively

### ISSUE THREAD

**Issue by masonrhayes** [cryptee/web-client#65]
**Describe the bug**
Ghost folders can be created as Untitled, allowing anyone with access to the Cryptee account to find any ghost folder **without** knowing the original folder name.

**To Reproduce**

1. After logging into your Cryptee account and typing the appropriate encryption key, upload a photo. 
2. Add this photo to an album.
3. Name the album
4. Ghost the album
5. At this step, the user is required to copy the title of the folder exactly as it is named in step 3
6. Now, summon the ghost album
7. Ghost the album again
Here's the issue: at this step (step 7), the user is no longer required type the correct album name, or to enter any album name at all

**Expected behavior**
User should always be prompted to retype the name of the ghost album, or at least to acknowledge that he/she wants the album to remain untitled

**Recording of the Issue**
I've captured all steps of the issue in this video:
https://youtu.be/Bw3W-T4geRI

**System Information (please complete the following information):**
 - Device: Asus Laptop
 - OS: Windows 10
 - Browser: Brave Browser
 - Browser Version: Latest
 - Browser Extensions / Add-ons / Content Blockers: ublock, privacy badger, cookie autodelete, and more.
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there! 

Fantastic catch! 🙌🏻Many million thanks for filing this! 
The video was immensely helpful. 

Fixed this in the alpha version now, and working on an automatic test to catch and prevent this from happening in the future. The fix will be released to public/live channel with the upcoming release in the next few days. 

---

In case if you're wondering how & why we missed this – The test we had in place was first ghosting an album then summoning it to make sure the modal is working & ghost / summon features are working in general. It wasn't testing twice in the same session – so the automated test missed that the green confirm button isn't disabled/reset after it's enabled once during the session. 

---

I've linked this issue in our internal release system, so once the update is out, this issue will be closed automatically, and you'll get a notification! 

Thanks a million again! ✌🏻

Best,
J
