### ISSUE TITLE
Files take double amount of space when uploaded to cryptee

### ISSUE THREAD

**Issue by domanteli0** [cryptee/web-client#67]
**Describe the bug**
Then I upload a file the upload dialog (The amount of space taken meter at the home page also increases by double the size of that file) shows what that file takes double amount of space than windows explorer or Firefox download dialog.

**To Reproduce:**
1. Upload a file
2. Observe the final file size

**Expected behavior**
I expect the file to take the same amount of space as it does in other places.

**Screenshots**
![gif](https://user-images.githubusercontent.com/49041398/83908136-19cb4780-a756-11ea-8b08-9c39a0934004.gif)

**System Information (please complete the following information):**
 - Device: Mid-end AMD-based PC with keyboard and mouse, no touch.
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 77.0.1 (64-bit)
 - Browser Extensions / Add-ons / Content Blockers: Enchanced Tracking Protection, Nextcloud Passwords, uBlock Origin, Privacy Badger, HTTPS Everywhere, Decentraleyes, Multi-Account Containers (only use it for Facebook, Google, Reddit, Twitter)
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No

**Comment by johnozbay** [comment]
Hi there! ✌🏻
Please take a look at this: 
https://crypt.ee/help?article=why-are-my-files-larger-on-cryptee-than-on-my-device
