### ISSUE TITLE
[Bug] On iOS, selecting text from left to right triggers the folder panel to open

### ISSUE THREAD

**Issue by dhda** [cryptee/web-client#70]
Hello hello! I have some more bugs to file.

**Describe the bug**
On iOS, selecting text from left to right triggers the folder panel to open. No matter how slowly I drag my finger, it seems to be registered as a swipe.

**To Reproduce**
1. Enter some text
2. Select the first word on the line
3. Drag to expand the selection to the right
4. Folder panel opens

**Expected behavior**
The document doesn't fly away and I'm able to select text from left to right.

**Screenshots**
![Image-2](https://user-images.githubusercontent.com/273696/84335251-4c57b480-ab49-11ea-8634-c7a5591c50ba.gif)

**System Information:**
 - Device: iPhone 6s
 - OS: iOS 13.4.1
 - Browser Safari–PWA installed to home screen

**Comment by johnozbay** [comment]
Hi there! Wow! thanks a million for filing these bugs! Immensely helpful! 
Looks like iOS 13.3 broke this by changing the way it handles text selection. 

Previously, when text is selected, editor would stay 'in focus', and swipes would be registered in the editor. Looks like as of iOS 13.3 when you select text, the editor now loses focus instead, and the swipe registers on the whole app, triggering a menu open. 

I've fixed this in the alpha version now and linked this issue to our internal issue/release tracker.
Once the update with this fix is out (should be in a few days), this issue will be closed automatically, and you'll get a notification!

Thank you so much for your help and patience!
Best,
J

**Comment by dhda** [comment]
Thank you!! 💜
