### ISSUE TITLE
Firefox Beta / Nightly / Preview Rendering Issues

### ISSUE THREAD

**Issue by astarq** [cryptee/web-client#79]
**Describe the bug**
Sizing of the toolbar editor is off. 
Triple-dot menu (on folders) is hidden until tapped
See screenshots... 

**To reproduce**
Open cryptee in a chromium based browser, and one based on geckoview
**Expected behavior**
👀

**Screenshots**
![Screenshot_20200627-131901_Firefox-01](https://user-images.githubusercontent.com/63871973/85922162-19b3f880-b879-11ea-8283-37dfd55235bf.jpeg)
![Screenshot_20200627-130536_Firefox-01](https://user-images.githubusercontent.com/63871973/85922270-f9386e00-b879-11ea-91f4-8a94c61b109d.jpeg)
![Screenshot_20200627-131857_Firefox](https://user-images.githubusercontent.com/63871973/85922273-fccbf500-b879-11ea-9ea4-fd55221ebf8b.png)

**System Information (please complete the following information):**
 - Device: Samsung Galaxy S8+ 
 - OS: Android 10
 - Browser: Firefox Beta, Firefox Nightly
 - Browser Version: 78.0.1-beta.1 
 - Browser Extensions: Ublock Origin (disabled for crypt.ee), Search by Image, Dark Reader (disabled) 

**Additional context**
Sadly this has nothing to do with font size :/

**Comment by johnozbay** [comment]
Hi there! ✌🏻

This seems a lot like a Firefox Nightly / Beta / Preview bug. 
If possible could you please check to see if you're experiencing the same problem with the non-beta Firefox? 

Cryptee's layout system relies heavily on detecting your device's pointer / touch capabilities, and if the browser isn't reporting it correctly (or an extension is interfering with the detection) you might have all sorts of unexpected layout issues. 

Thanks ✌🏻

**Comment by astarq** [comment]
Hi, thanks for the speedy reply! 

I just checked Fennec and it renders normally,  accept for the triple dot menu which I mentioned. 
Thanks!

**Comment by johnozbay** [comment]
You're very welcome! ✌🏻

What you're experiencing sounds a lot like a FF Preview / Nightly bug. 

I'll run a few more tests for the dots to see if it's on us, and if it is, we'll fix it up ASAP. 

I'll close this for now – and needless to say feel free to ping me again here if you bump into other similar bugs. ✌🏻

Thanks a million! 🎉

**Comment by astarq** [comment]
I'll file a bug on the Fenix repo as well 

Thanks again, I really appreciate it! ✌

**Comment by johnozbay** [comment]
Thank _you_! Deeply appreciate all the help! Super thankful and grateful for all these bug reports! ✌🏻
