### ISSUE TITLE
[Feature] Full Dark Mode

### ISSUE THREAD

**Issue by brendanperry** [cryptee/web-client#82]
Even with dark mode enabled, the background for documents is still white. On mobile, this just makes the whole screen white. I'd like to see the dark mode work on documents as well or at least an option for it.

**Comment by bobleeSwagger2** [comment]
I agree. The implementation that Google just did with docs looks nice

**Comment by johnozbay** [comment]
Hi there folks 👋🏻 
Would be fantastic if we can continue this conversation here : https://github.com/cryptee/web-client/issues/20 where I've talked intensely about why this isn't possible. 

If you have any ideas about how to address the challenges I mentioned there, I'd be happy to make it happen with our upcoming V3 update (complete re-factoring & re-design of the entire service)

Thanks ✌🏻
