### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [cryptee/web-client#84]

**Comment by johnozbay** [comment]
Hi there, 

This feature already exists. 

You can read about how to link documents/files to your documents here on our helpdesk : 
https://crypt.ee/help?article=how-can-i-link-attach-files-or-documents-to-documents

Best,
John

**Comment by alanrxs** [comment]
Hi, sorry I didn't explain that well.

I'm requesting a feature to create a link to a cryptee note inside of another cryptee note.

So in cryptee I have Note1 and Note2. I want to create a link to Note2 within Note1.

Is this possible?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
