### ISSUE TITLE
[Feature Request] Solarized light/dark theme

### ISSUE THREAD

**Issue by BasilTomato** [cryptee/web-client#91]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
This may be a personal taste but working multiple hours with black and white color scheme is quite tiresome.
Would it be possible to implement the Solarized light/dark theme as and alternative for the current black & white scheme?
There are other similar color schemes out there, but I found this the most relaxing for the eyes.

**Additional context**
Further information: https://en.wikipedia.org/wiki/Solarized_(color_scheme)

**Comment by johnozbay** [comment]
Hi there! 

Today's v3.0 update also brings support for a full-dark mode editor and a different dark mode color scheme! Take a look at this ( https://github.com/cryptee/web-client/issues/20 ), give the new version ( 01edfe4 ) a try, and let me know if you like the new version's color scheme a bit better!

We'll be making incremental visual updates from now on, so let me know how you like this, and we'll slowly make improvements! 

All the best, ✌🏻

**Comment by BasilTomato** [comment]
Hello, thanks for the update!
The new design is definitely nicer.

**Comment by johnozbay** [comment]
Closed this for now, but please feel free to let me know if you can think of any specific areas we can improve with the color scheme, and we'll take a look at this again! 

Thanks a lot! ✌🏻
