### ISSUE TITLE
[Bug] Can't create additionals tags after first tag when on same line 

### ISSUE THREAD

**Issue by bluinch** [cryptee/web-client#95]
**Describe the bug**
Can't create a additional tags on the same line when I press enter key. Works if I try on a new line. Works if I click on the add tag popup. 

**To Reproduce**
1. Create a tag then create second tag on same line 
2. Press 'Enter' key 
3. No tag created

**Expected behavior**
Can create tags after the first tag, while on the same line, when I press the 'Enter' Key. 

**Screenshots**
![Screenshot 2020-12-28 at 10 53 47 PM](https://user-images.githubusercontent.com/25111698/103257581-c756b000-495f-11eb-9053-86881a0728f6.png)

**System Information (please complete the following information):**
 - Device: Chromebook
 - OS: Chrome OS
 - Browser: Chrome
 - Browser Version: 87.0.4280.109 (64-bit)
 - Browser Extensions / Add-ons / Content Blockers: uBlock Origin, Privacy Badger, Cookie AutoDelete, Third-party cookies blocked 
 - Do you have any DNS-based content blockers? No
 - Are you on a managed network? No 
 
**Additional context**
Disabled extensions and third-party cookie blocking, error still happening. Although a page refresh fixes it temporarily.

**Comment by johnozbay** [comment]
Hi there! 👋🏻
Thanks a lot for filing this, and apologies for the delay in responding to this! 

We've been busy working on our major v3 update, in which we've actually fixed this problem.  ( 01edfe472a72557aa2c323fc55a77e25612b0da4 ) 

![image](https://user-images.githubusercontent.com/611338/108849075-6dced280-75ea-11eb-9580-a9b03566e7c5.png)

The tags you see in the screenshot were created using "tab", "enter" and by clicking the add tag button. 

This should now work in all browsers & operating systems. 
I'll close this issue for now, but please feel free to comment / reopen it if you experience this again.

Many thanks ✌🏻
