### ISSUE TITLE
Can't upload AIF files

### ISSUE THREAD

**Issue by Yalaouf** [cryptee/web-client#96]
**Describe the bug**
I wanted to upload a aif file into my cryptee account, from my android 10 phone.
But everytime I try, the website crashes (the Aw Snap screen).

**To Reproduce**
1. Go to documents
2. Try to upload an AIF file anywhere
3. Briefly see an empty progress bar modal
4. See the error (Aw, Snap!)

**Expected behavior**
Normally I would have the progress bar processing, and then my new AIF file into my folder.

**Screenshots**
![Screenshot_20210201-110431](https://user-images.githubusercontent.com/59565408/106443970-7285e800-647d-11eb-980d-30d5e74c6afd.png)

**System Information (please complete the following information):**
 - Device: Sony Xperia 5ii
 - OS: Android 10
 - Browser Chrome
 - Browser 88.0.4324.93
 - Browser Extensions: none
 - Do you have any DNS-based content blockers? [i.e. pi-hole] No
 - Are you on a managed network? [e.g. VPN / Corporate Network] No

**Comment by ghost** [comment]
Hello! How big is the file you try to upload?
Because you can't upload files bigger than 50mb.

More details here: https://crypt.ee/help?article=how-large-of-a-file-can-i-upload

**Comment by Yalaouf** [comment]
Hey ! Thanks for the reply.
Yes the problem was from my file. It's way bigger than the 50mb cap.
I'll see the link and will wait for update about this limit in the near future.

Have a nice day !
